# NE111 Final Fall 2018

**Aids:** None. You may use tools such as Jupyter Notebook (without opening other files) and iPython, but access to the lecture/exercise content or the Internet is forbidden.

**Length**: 2 hours

**Instructions**:

*YOU ARE ASSUMED TO HAVE READ THE INSTRUCTIONS ON THE LEARN ANNOUNCEMENT AND ARE NOW ON STEP 6.*

1. Complete exam identification information in the following cell.
2. Complete exam problems. Each problem will give you instructions on how to complete it properly. **Periodically save your file to disk (CTRL+S).**
3. When you are finished, in this notebook, go to File -> Download As -> Python (.py). 
4. Move the downloaded file from the Downloads folder to N: (in the same folder that you placed `validate_final.py` earlier).
5. Validate your exam submission by opening a the *Anaconda Prompt*, navigating to the N: drive (refer back to steps 2 and 3 on LEARN), and executing (replace the `[name_of_final_file.py]` with your file, probably *final.py*):
> `python validate_final.py [name_of_final_file.py]`
6. If your submission validated successfully (please *read* the output), proceed to Step 7 on the LEARN announcement.

In [ ]:
# Enter your full name and student ID as strings
Student_Name = ""
Student_ID = ""

**Please remember to import NumPy before proceeding.** You are allowed to modify the import statement however you prefer.

In [ ]:
import numpy

## Problem 1 (5 points, 1 point each)

Fill in the blanks in each statement with a phrase from the table.

#### (Definitions)

You are given a table of terms used in the course.

|     |     |     |     |     |
|-----|-----|-----|-----|-----|
| dictionary | boolean | built-in function | operating system | dynamic |
| operator | broadcast | method | docstring | view |
| namespace | keyword | random-access memory | memory address | compiler |
| interpreter | module | comment | variable | deep copy |


Match each blank (`______`) below to its *best / closest* term in the table (there are more terms than definitions). Do not consider the surrounding grammar when choosing your answer. The first answer is filled in for you as a demonstration.

**Example.** A/an `______` is used in a function declaration to provide a description of the function's behaviour. (**Answer**: `docstring`.)

**I.** The  `Python` programming language supports `______` types.

**II.** `______` arguments of functions do not need to be explicitly specified.

**III.** A `______` of an `ndarray` creates both a new array object and data.

**IV.** The built-in `help()`function allows you to access the `______` of an object.

**V.** Using the `asmatrix()` function returns a `______` of an array with type `matrix`.

In [ ]:
def_example = "docstring"  # Example. Use the EXACT string given in the table.
def_i = ""
def_ii = ""
def_iii = ""
def_iv = ""
def_v = ""

## Problem 2 (5 points, 1 point each)

Select the correct answer(s) from the set of choices.

**I.** Given the matrix $A$, what is the sum of all of the elements of its invert $A^{-1}$?

$$ 
A = \left[ \begin{array}{cccc}
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16 \\
17 & 18 & 19 & 20 \\\end{array} \right], \quad 
B = (A)(A^T) 
$$

>**a)** 1.2
>**b)** 3.7
>**c)** -0.1
>**d)** 0.1
>**e)** None of the above

**II.** Given the shape attributes of various pairs of NumPy arrays, select those for which binary operators can broadcast:

>**a)** `(2, 2)` and `(2, 1)`
>**b)** `(4, 5, 6)` and `(5, 6)`
>**c)** `(1, 4, 5)` and `(5,)`
>**d)** `(2, 2, 2)` and `(2, 2)`

**III.** Which of the following collection types can be used to create unordered collections?.

>**a)** `list`
>**b)** `string`
>**c)** `set`
>**d)** `ndarray`
>**e)** `dict`


**IV.** What is the name of the `ndarray` method which is used to "Return indices of the minimum values along the given axis of `a`."?

>**a)** `mean`
>**b)** `min`
>**c)** `max`
>**d)** `all`
>**e)** None of the above


**V.** Which statements are *true* regarding the following block of code?
```
def print_metallica(n):
    for i in range(0, N):
        print("METALLICA")
```
>**a)** There is a syntax error in this block of code.  
>**b)** Calling `print_metallica(3)` returns the string `"METALLICA\nMETALLICA\nMETALLICA\n"`.  
>**c)** The variable `i` is only defined in the namespace of the `for` loop.  
>**d)** Calling `print_greeting(3)` will produce an error.


In [ ]:
mc_i = ""  # "", "a", "ab", etc.
mc_ii = ""
mc_iii = ""
mc_iv = ""
mc_v = ""

## Problem 3 (5 points, 1 point each)

Determine whether the statements are True or False.

**I.** An `ndarray` can have an unlimited number of views associated with it.

**II.** Given a `str` object `my_string`, both `str.capitalize(my_string)` and `my_string.capitalize()` can be used to capitalize `my_string`.

**III.** All `for` loops may be re-written using a `while` loop, but not vice-versa.

**IV.** Slicing an `ndarray` has no affect on the data associated with that array.

**V.** `matplotlib` is the official plotting library for the Python programming language.

In [ ]:
tf_i = None  # True or False
tf_ii = None
tf_iii = None
tf_iv = None
tf_v = None

## Problem 4 (10 points)

Develop a function `pythagorean_triple(a, b)` described by the following docstring:

```python
"""(float, float) -> (float, float, float)
    
Given input arguments (a, b) return the Pythagorean triple (a, b, c) where,

a^2 +  b^2 = c^2

where if invalid input arguments are provided the function returns None.
    
>>> pythagorean_triple(3., 4.)
(3.0, 4.0, 5.0)
>>> pythagorean_triple(3, 4.)
None
>>> pythagorean_triple("METALLICA", 1.)
None
"""  
```

In [ ]:
def pythagorean_triple(a, b):
    pass # replace this statement with your code

## Problem 5 (10 points)

Develop a function `input_and_loop()` described by the following docstring:

```python
"""(str) -> None
    
Query the user first for a string to repeat and then for the number of repetitions then print the string for that number of repetitions. Return None of the number of repetitions inputted by the user is not numeric (using str.isnumeric).
    
>>> input_and_loop()
Input loop string: METALLICA
Input number of repetitions: 3
METALLICA
METALLICA
METALLICA
>>> input_and_loop()
Input loop string: METALLICA
Input number of repetitions: infinity
None
"""  
```

In [1]:
def input_and_loop():
    pass # replace this statement with your code

## Problem 6 (15 points)

Develop a function `project_to_grid(func, xlim, ylim, N)` described by the following docstring:

```python
"""(function, float, float, int) -> (ndarray, ndarray, ndarray)
    
Returns ndarrays (f, x, y) all of shape (N, N) where x and y are the x- and y-coordinates equally spaced over the intervals [0, xlim] and [0, ylim], respectively. The ndarray f is the result of evaluating the function argument at each of these points assuming the function argument type contract is,

(float, float) -> float


>>> def func(x, y):
    return(x*y)
    
>>> project_to_grid(func, 10., 10., 3)
(array([[  0,   0,   0],
       [  0,  25,  50],
       [  0,  50, 100]]),
 array([[ 0,  5, 10],
        [ 0,  5, 10],
        [ 0,  5, 10]]),
 array([[ 0,  0,  0],
        [ 5,  5,  5],
        [10, 10, 10]]))
"""  
```

In [ ]:
def func(x, y):
    return(x*y)

def project_to_grid(func, xlim, ylim, N):
    pass # replace this statement with your code